@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class UniqueCompanyList

package "package: companies"{
Class Company
Class CompanyName
Class CompanyPhone
Class CompanyEmail
Class Description
Class Tag
Class Internship
}


UniqueCompanyList -right-> "~* all" Company
Company *--> "1" CompanyName
Company *--> "1" CompanyPhone
Company *--> "1" CompanyEmail
Company *--> "1" Description
Company *--> "*" Tag
Company *--> "*" Internship

@enduml
