@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class UniqueCompanyList

package "package: companies"{
Class Company
Class CompanyName
Class CompanyPhone
Class CompanyEmail
Class Description
Class Tag
}

package "package: companies.package: internship" {
Class Internship
Class InternshipName
Class InternshipDescription
Class InternshipInterviewDateTime
}


UniqueCompanyList -down-> "~* all" Company
Company *--> "1" CompanyName
Company *--> "1" CompanyPhone
Company *--> "1" CompanyEmail
Company *--> "1" Description
Company *--> "*" Tag
Company *--> "*" Internship

Internship *--> "1" InternshipName
Internship *--> "1" InternshipDescription
Internship *--> "0..1" InternshipInterviewDateTime

@enduml
