@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCompanyCommand" as DeleteCompanyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete c 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete c 1")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse("c 1")
activate DeleteCommandParser

create DeleteCompanyCommand
DeleteCommandParser -> DeleteCompanyCommand
activate DeleteCompanyCommand

DeleteCompanyCommand --> DeleteCommandParser : d
deactivate DeleteCompanyCommand

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCompanyCommand : execute()
activate DeleteCompanyCommand

DeleteCompanyCommand -> Model : deleteCompany(1)
activate Model

Model --> DeleteCompanyCommand
deactivate Model

create CommandResult
DeleteCompanyCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCompanyCommand
deactivate CommandResult

DeleteCompanyCommand --> LogicManager : result
deactivate DeleteCompanyCommand

[<--LogicManager
deactivate LogicManager
@enduml
