@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ViewDisplay
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class StatusBarFooter
Class CommandBox
Class CompanyListPanel
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ...> Ui

UiManager .left.|> Ui
UiManager -down--> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" ViewDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down--> "1" CompanyListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
ViewDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
CompanyListPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

UiManager -up-> Logic
MainWindow -up-> Logic

CompanyListPanel -[hidden]left- PersonListPanel
PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ViewDisplay
ViewDisplay -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
