@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:ViewPersonCommand" as ViewPersonCommand LOGIC_COLOR
end box

[-> LogicManager : execute("view p 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("view p 1")
activate AddressBookParser

create ViewCommandParser
AddressBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> AddressBookParser
deactivate ViewCommandParser

AddressBookParser -> ViewCommandParser : parse("p 1")
activate ViewCommandParser

create ViewPersonCommand
ViewCommandParser -> ViewPersonCommand
activate ViewPersonCommand

ViewPersonCommand --> ViewCommandParser : v
deactivate ViewPersonCommand

ViewCommandParser --> AddressBookParser : v
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> AddressBookParser
destroy ViewCommandParser

AddressBookParser --> LogicManager : v
deactivate AddressBookParser

LogicManager -> ViewPersonCommand : execute()
activate ViewPersonCommand

ref over ViewPersonCommand
Retrieve person to view from list of persons
end ref

ViewPersonCommand --> LogicManager : result
deactivate ViewPersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
